# Generated by Django 5.1 on 2024-08-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="balance_after",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
